name: Windows-CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: PyInstaller Linux
        uses: JackMcKew/pyinstaller-action-linux@0.1.4
        
      - uses: actions/upload-artifact@v2
        with:
          name: HeadsetControl-SystemTray
          path: src/dist/HeadsetControl_SystemTray
